#----------Networks----------#

networks:
  inception:
    name: inception

#----------Volumes----------#

volumes:
  volume_mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: "/home/dhuss/data/mariadb"
      o: bind
  volume_wp_nginx:
    name: wp_nginx
    driver: local
    driver_opts:
      type: none
      device: "/home/dhuss/data/wp_nginx"
      o: bind
  volume_portainer:
    name: portainer_data
    driver: local
    driver_opts:
      type: none
      device: "/home/dhuss/data/portainer"
      o: bind

#----------Secrets----------#

secrets:
  db_pw:
    file: ../secrets/db_pw.txt
  db_root_pw:
    file: ../secrets/db_root_pw.txt
  wp_pw:
    file: ../secrets/wp_user_pw.txt
  wp_admin_pw:
    file: ../secrets/wp_admin_pw.txt
  portainer_admin_pw:
    file: ../secrets/portainer_admin_pw.txt
  ftp_pw:
    file: ../secrets/ftp_pw.txt

#----------Services----------#

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - ./.env
    volumes:
      - volume_mariadb:/var/lib/mysql
    secrets:
      - db_pw
      - db_root_pw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      start_period: 7s
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - inception

#----------Wordpress----------#

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    secrets:
      - wp_pw
      - wp_admin_pw
      - db_pw
    healthcheck:
      test: ["CMD-SHELL", "wp core is-installed --path=/var/www/html/dhuss.42.fr/public_html --allow-root"]
      start_period: 10s
      interval: 2s
      timeout: 5s
      retries: 7
    env_file:
       - ./.env
    volumes:
       - volume_wp_nginx:/var/www/html

#----------Nginx----------#

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception
    volumes:
      - volume_wp_nginx:/var/www/html

#----------Bonus----------#

#----------adminer----------#
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception

#----------redis cache----------#
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception

#----------static website----------#
  website:
    container_name: website
    build: ./requirements/bonus/website
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception

#----------ftp----------#
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    ports:
      - 21:21
      - 40000-40010:40000-40010
    restart: always
    networks:
      - inception
    env_file:
      - ./.env
    secrets:
      - ftp_pw
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
       - volume_wp_nginx:/var/www/html

#----------portainer----------#

  portainer:
    container_name: portainer
    build: ./requirements/bonus/portainer
    ports:
      - 9443:9443
    restart: always
    networks:
      - inception
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - volume_portainer:/data
    secrets:
       - portainer_admin_pw