FROM debian:bullseye

RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y php-fpm && \
	apt-get install -y mariadb-client && \
	apt-get install -y curl && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

COPY	./setup_wordpress.sh /setup_wordpress.sh
RUN		chmod +x /setup_wordpress.sh

ENTRYPOINT ["/setup_wordpress.sh"]