FROM debian:bullseye

RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y nginx && \
	apt-get install openssl && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

# copy this file into conf.d because the main nginx config file has "include /etc/nginx/conf.d/*.conf;"
# any valid config file with a server block will run
COPY ./custom.conf	/etc/nginx/conf.d/custom.conf

COPY ./openssl.cnf /etc/nginx/ssl/openssl.cnf
COPY ./start_nginx.sh /start_nginx.sh

# grant rights to execute script & use openssl.cnf for automatic prompt answering during key gen
RUN chmod +x /start_nginx.sh
RUN chmod +x /etc/nginx/ssl/openssl.cnf

ENTRYPOINT ["/start_nginx.sh"]